# Generated by Django 2.2.5 on 2019-11-07 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0002_usercontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontacts',
            name='current_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='email_address',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
