# Generated by Django 2.2.5 on 2019-11-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20191107_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='email_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='street_address',
            field=models.CharField(max_length=350),
        ),
    ]
