# Generated by Django 2.2.7 on 2019-11-19 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0005_auto_20191107_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontacts',
            options={'ordering': ['owner', 'last_name', 'first_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='usercontacts',
            name='current_user',
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
